export const swiatWeb3BlogPosts = [
  {
    title: 'Disco - zdecentralizowana tożsamość',
    date: '2022-08-18T17:35:03.794Z',
    path: 'https://swiatweb3.substack.com/p/disco-zdecentralizowana-tozsamosc',
    author: 'Świat Web3',
    authorLink: 'https://swiatweb3.substack.com/',
    summary: 'Dlaczego zdecentralizowana tożsamość zastąpi Gmaila?',
    category: 'Article',
    tags: ['Świat Web 3'],
    image: '/blog/previews/disco-zdecentralizowana-tozsamosc.webp',
  },
  {
    title: 'Internet Computer (ICP)',
    date: '2022-08-11T17:35:03.794Z',
    path: 'https://swiatweb3.substack.com/p/internet-computer-icp',
    author: 'Świat Web3',
    authorLink: 'https://swiatweb3.substack.com/',
    summary: 'A co jakby tak zdecentralizować cały internet?',
    category: 'Article',
    tags: ['Świat Web 3'],
    image: '/blog/previews/internet-computer-icp.png',
  },
  {
    title: 'Polygon',
    date: '2022-08-04T17:35:03.794Z',
    path: 'https://swiatweb3.substack.com/p/polygon',
    author: 'Świat Web3',
    authorLink: 'https://swiatweb3.substack.com/',
    summary: 'Dlaczego sieci Layer2 są konkurencją dla Layer1?',
    category: 'Article',
    tags: ['Świat Web 3'],
    image: '/blog/previews/polygon.png',
  },
  {
    title: 'Dogecoin',
    date: '2022-07-28T17:00:58.630Z',
    path: 'https://swiatweb3.substack.com/p/dogecoin',
    author: 'Świat Web3',
    authorLink: 'https://swiatweb3.substack.com/',
    summary: 'A co jakby z mema zrobić kryptowalutę?',
    category: 'Article',
    tags: ['Świat Web 3'],
    image: '/blog/previews/doge.png',
  },
  {
    title: 'Decentraland',
    date: '2022-07-21T17:00:15.497Z',
    path: 'https://swiatweb3.substack.com/p/decentraland',
    author: 'Świat Web3',
    authorLink: 'https://swiatweb3.substack.com/',
    summary: 'Czy metaverse Decentraland opanuje całe web3?',
    category: 'Article',
    tags: ['Świat Web 3'],
    image: '/blog/previews/decentraland.png',
  },
  {
    title: 'Bezpieczeństwo w Web3',
    date: '2022-07-15T10:25:00.310Z',
    path: 'https://swiatweb3.substack.com/p/bezpieczenstwo-w-web3',
    author: 'Świat Web3',
    authorLink: 'https://swiatweb3.substack.com/',
    summary: 'Czy blockchain jest wystarczająco bezpieczny?',
    category: 'Article',
    tags: ['Świat Web 3'],
    image: '/blog/previews/security.jpg',
  },
  {
    title: 'AAVE',
    date: '2022-07-07T17:00:10.286Z',
    path: 'https://swiatweb3.substack.com/p/aave',
    author: 'Świat Web3',
    authorLink: 'https://swiatweb3.substack.com/',
    summary: 'Dlaczego protokoły DeFi to koszmar bankierów?',
    category: 'Article',
    tags: ['Świat Web 3'],
    image: '/blog/previews/aave.png',
  },
  {
    title: 'Audius',
    date: '2022-06-30T17:00:14.124Z',
    path: 'https://swiatweb3.substack.com/p/audius',
    author: 'Świat Web3',
    authorLink: 'https://swiatweb3.substack.com/',
    summary: 'A gdyby tak zdecentralizować platformy streamingowe?',
    category: 'Article',
    tags: ['Świat Web 3'],
    image: '/blog/previews/audius.png',
  },
  {
    title: 'NBA Top Shot',
    date: '2022-06-23T17:00:20.022Z',
    path: 'https://swiatweb3.substack.com/p/nba-top-shot',
    author: 'Świat Web3',
    authorLink: 'https://swiatweb3.substack.com/',
    summary: 'Projekt NFT za 3 punkty?',
    category: 'Article',
    tags: ['Świat Web 3'],
    image: '/blog/previews/topshot.png',
  },
  {
    title: "Stellar - następca SWIFT'u czy tylko kopia XRP?",
    date: '2022-06-16T17:00:23.866Z',
    path: 'https://swiatweb3.substack.com/p/stellar-nastepca-swiftu-czy-tylko',
    author: 'Świat Web3',
    authorLink: 'https://swiatweb3.substack.com/',
    summary:
      'Witaj w trzeciej odsłonie newslettera Świat Web3, w którym dwójka pasjonatów stara się rozwikłać zagadki technologii blockchain, metaverse, DeFi oraz…',
    category: 'Article',
    tags: ['Świat Web 3'],
    image: '/blog/previews/stellar.png',
  },
  {
    title: 'Algorand - czy Blockchain Trillema naprawdę istnieje?',
    date: '2022-06-06T18:23:34.663Z',
    path: 'https://swiatweb3.substack.com/p/algorand-czy-blockchain-trillema',
    author: 'Świat Web3',
    authorLink: 'https://swiatweb3.substack.com/',
    summary:
      'Witaj w drugiej odsłonie newslettera Świat Web3, w którym dwójka pasjonatów stara się rozwikłać zagadki technologii blockchain, metaverse, DeFi oraz…',
    category: 'Article',
    tags: ['Świat Web 3'],
    image: '/blog/previews/algorand.png',
  },
  {
    title: 'Quantstamp - audyt i bezpieczeństwo w Web 3.0',
    date: '2022-05-16T23:03:10.534Z',
    path: 'https://swiatweb3.substack.com/p/quantstamp-audyt-i-bezpieczenstwo',
    author: 'Świat Web3',
    authorLink: 'https://swiatweb3.substack.com/',
    summary: 'Czy samo bezpieczeństwo blockchainów wystarczy?',
    category: 'Article',
    tags: ['Świat Web 3'],
    image: '/blog/previews/quantstamp.png',
  },
];
