export enum COLOR { //names generated by https://colornamer.robertcooper.me/
  VIOLET = '#9404FC',
  PURPLE = '#6802b1',
  GREY = '#333333',
  UNIFORM_GREY = '#8A8A8A',
  BLACK = '#010001',
  WHITE = '#FFFFFF',
  MYSTERIOUS_DEPTHS = '0D0D2B',
  SUCCESS_GREEN = '#4CB963',
  FAIL_RED = '#FE5F55',
}

export const basicTheme = {
  hederHeight: 64,
  contentWidth: 1250,
  maxWidth: 800,
  fontFamily: "'Inter', sans-serif",
};
